# SITE CONFIGURATION
title: Denis Germano
author: Denis Germano
description: > # Meta description of Homepage
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://denisgermano.github.io/" # the base hostname & protocol

# SEO PLUGIN
social:
  name: Denis Germano
  links:
    - https://twitter.com/denisgermano
    - https://www.facebook.com/denisgermano
    - https://www.linkedin.com/in/denisgermano
    - https://github.com/denisgermano

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}

tagline: >
  Modern Jekyll theme focused on speed performance &amp; SEO best practices

hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: dlcgermano@gmail.com # email for form submission

twitter_username: denisgermano
github_username:  denisgermano
instagram_username: denisgermano

disqus:
  shortname: denisgermano

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
